import type { OwnerWithdrawalSource } from '@/types';
import { STOCK_PURCHASE_DEDUCTION_START_DATE } from './barMoney';
import type { StockPurchaseCostRow } from './barMoney';
import type {
  DailyCashRow,
  DebtPaymentValueRow,
  ExpenseRow,
  StockCountRow,
} from './dashboardMetrics';

export interface AvailableMoneyWithdrawalRow {
  id?: string;
  date: string;
  source: OwnerWithdrawalSource;
  amount: number;
  created_at?: string;
}

export interface CalculateAvailableMoneyInput {
  cashRows: DailyCashRow[];
  stockRows: StockCountRow[];
  purchaseRows: StockPurchaseCostRow[];
  expenseRows: ExpenseRow[];
  debtPaymentRows?: DebtPaymentValueRow[];
  withdrawalRows?: AvailableMoneyWithdrawalRow[];
  /** Include ledger rows dated on or before this ISO date. Omit for all rows. */
  throughDate?: string;
}

export interface AvailableSourceBalance {
  /** Cumulative cash generated by this source after its source-specific costs. */
  earned: number;
  withdrawn: number;
  /** Retained balance. This remains negative when the ledger is overdrawn. */
  available: number;
  overdrawnBy: number;
}

export interface InvalidOwnerWithdrawal {
  id?: string;
  date: string;
  source: OwnerWithdrawalSource;
  amount: number;
  availableBefore: number;
  overdrawnBy: number;
}

export interface AvailableMoneyResult {
  gameClub: AvailableSourceBalance;
  bar: AvailableSourceBalance;
  totalEarned: number;
  totalWithdrawn: number;
  totalAvailable: number;
  hasOverWithdrawal: boolean;
  /** Withdrawals that exceeded the source balance available on their date. */
  invalidWithdrawals: InvalidOwnerWithdrawal[];
}

function numericAmount(value: number): number {
  return Number(value ?? 0);
}

function isIncluded(date: string, throughDate?: string): boolean {
  return throughDate === undefined || date <= throughDate;
}

function withdrawalAmount(row: AvailableMoneyWithdrawalRow): number {
  const amount = numericAmount(row.amount);

  if (!Number.isFinite(amount) || amount <= 0) {
    throw new RangeError('Withdrawal amount must be a finite number greater than zero');
  }

  return amount;
}

/**
 * Computes retained owner balances across the full supplied history. Monthly
 * carry-over happens naturally: income is recognized once and remains available
 * until a source-specific withdrawal consumes it.
 */
export function calculateAvailableMoney({
  cashRows,
  stockRows,
  purchaseRows,
  expenseRows,
  debtPaymentRows = [],
  withdrawalRows = [],
  throughDate,
}: CalculateAvailableMoneyInput): AvailableMoneyResult {
  const includedCashRows = cashRows.filter((row) => isIncluded(row.date, throughDate));
  const includedStockRows = stockRows.filter((row) => isIncluded(row.date, throughDate));
  const includedPurchaseRows = purchaseRows.filter((row) => isIncluded(row.date, throughDate));
  const includedExpenseRows = expenseRows.filter((row) => isIncluded(row.date, throughDate));
  const includedDebtPaymentRows = debtPaymentRows.filter((row) => isIncluded(row.date, throughDate));
  const includedWithdrawalRows = withdrawalRows.filter((row) => isIncluded(row.date, throughDate));

  // Validate all included withdrawal amounts before aggregating them. Invalid
  // negative rows must never increase the available balance.
  includedWithdrawalRows.forEach(withdrawalAmount);

  const earnedThrough = (source: OwnerWithdrawalSource, date?: string): number => {
    const through = (rowDate: string) => date === undefined || rowDate <= date;
    const sourceExpenses = includedExpenseRows.reduce(
      (sum, row) => {
        const paymentSource = row.payment_source === 'bar' ? 'bar' : 'game_club';
        return paymentSource === source && through(row.date)
          ? sum + numericAmount(row.amount)
          : sum;
      },
      0,
    );

    if (source === 'game_club') {
      const collections = includedCashRows.reduce(
        (sum, row) => through(row.date)
          ? sum
            + numericAmount(row.cash_income)
            + numericAmount(row.terminal_income)
            + numericAmount(row.card_income)
            + numericAmount(row.playstation_income ?? 0)
          : sum,
        0,
      );
      const debtCollections = includedDebtPaymentRows.reduce(
        (sum, row) => through(row.date) ? sum + numericAmount(row.amount) : sum,
        0,
      );

      return collections + debtCollections - sourceExpenses;
    }

    const barSales = includedStockRows.reduce(
      (sum, row) => through(row.date) ? sum + numericAmount(row.bar_income) : sum,
      0,
    );
    const qualifyingPurchases = includedPurchaseRows.reduce(
      (sum, row) => row.date >= STOCK_PURCHASE_DEDUCTION_START_DATE && through(row.date)
        ? sum + numericAmount(row.quantity) * numericAmount(row.cost_price)
        : sum,
      0,
    );

    return barSales - qualifyingPurchases - sourceExpenses;
  };

  const withdrawalsBySource: Record<OwnerWithdrawalSource, number> = {
    game_club: 0,
    bar: 0,
  };
  for (const row of includedWithdrawalRows) {
    withdrawalsBySource[row.source] += withdrawalAmount(row);
  }

  const gameClubEarned = earnedThrough('game_club');
  const barEarned = earnedThrough('bar');
  const gameClubAvailable = gameClubEarned - withdrawalsBySource.game_club;
  const barAvailable = barEarned - withdrawalsBySource.bar;

  const indexedWithdrawals = includedWithdrawalRows
    .map((row, index) => ({ row, index }))
    .sort((a, b) =>
      a.row.date.localeCompare(b.row.date)
      || (a.row.created_at ?? '').localeCompare(b.row.created_at ?? '')
      || (a.row.id ?? '').localeCompare(b.row.id ?? '')
      || a.index - b.index,
    );
  const priorWithdrawals: Record<OwnerWithdrawalSource, number> = {
    game_club: 0,
    bar: 0,
  };
  const invalidWithdrawals: InvalidOwnerWithdrawal[] = [];

  for (const { row } of indexedWithdrawals) {
    const amount = withdrawalAmount(row);
    const availableBefore = earnedThrough(row.source, row.date) - priorWithdrawals[row.source];
    const availableAfter = availableBefore - amount;

    if (availableAfter < 0) {
      invalidWithdrawals.push({
        id: row.id,
        date: row.date,
        source: row.source,
        amount,
        availableBefore,
        overdrawnBy: -availableAfter,
      });
    }

    priorWithdrawals[row.source] += amount;
  }

  return {
    gameClub: {
      earned: gameClubEarned,
      withdrawn: withdrawalsBySource.game_club,
      available: gameClubAvailable,
      overdrawnBy: Math.max(0, -gameClubAvailable),
    },
    bar: {
      earned: barEarned,
      withdrawn: withdrawalsBySource.bar,
      available: barAvailable,
      overdrawnBy: Math.max(0, -barAvailable),
    },
    totalEarned: gameClubEarned + barEarned,
    totalWithdrawn: withdrawalsBySource.game_club + withdrawalsBySource.bar,
    totalAvailable: gameClubAvailable + barAvailable,
    hasOverWithdrawal: invalidWithdrawals.length > 0,
    invalidWithdrawals,
  };
}
