import type { OwnerWithdrawalSource } from '@/types';
import { STOCK_PURCHASE_DEDUCTION_START_DATE } from './barMoney';
import type { StockPurchaseCostRow } from './barMoney';
import type {
  DailyCashRow,
  DebtPaymentValueRow,
  ExpenseRow,
  StockCountRow,
} from './dashboardMetrics';

export interface AvailableMoneyWithdrawalRow {
  id?: string;
  /** First day of the calendar month represented by this withdrawal. */
  period_month: string;
  source: OwnerWithdrawalSource;
  amount: number;
  created_at?: string;
}

export interface CalculateAvailableMoneyInput {
  cashRows: DailyCashRow[];
  stockRows: StockCountRow[];
  purchaseRows: StockPurchaseCostRow[];
  expenseRows: ExpenseRow[];
  debtPaymentRows?: DebtPaymentValueRow[];
  withdrawalRows?: AvailableMoneyWithdrawalRow[];
  /** Include operating rows dated on or before this ISO date. Omit for all rows. */
  throughDate?: string;
}

export interface CalculateAvailableMoneyForMonthInput
  extends Omit<CalculateAvailableMoneyInput, 'throughDate'> {
  /** Calendar month in YYYY-MM format. */
  month: string;
}

export interface AvailableSourceBalance {
  /** Cash generated by this source after its source-specific costs. */
  earned: number;
  withdrawn: number;
  /** Retained balance. This remains negative when the ledger is overdrawn. */
  available: number;
  overdrawnBy: number;
}

export interface InvalidOwnerWithdrawal {
  id?: string;
  period_month: string;
  source: OwnerWithdrawalSource;
  amount: number;
  availableBefore: number;
  overdrawnBy: number;
}

export interface AvailableMoneyResult {
  gameClub: AvailableSourceBalance;
  bar: AvailableSourceBalance;
  totalEarned: number;
  totalWithdrawn: number;
  totalAvailable: number;
  hasOverWithdrawal: boolean;
  /** Withdrawals that exceeded their source balance within their month. */
  invalidWithdrawals: InvalidOwnerWithdrawal[];
}

export type AvailableMoneyByMonth = Record<string, AvailableMoneyResult>;

function numericAmount(value: number): number {
  return Number(value ?? 0);
}

function withdrawalAmount(row: AvailableMoneyWithdrawalRow): number {
  const amount = numericAmount(row.amount);

  if (!Number.isFinite(amount) || amount <= 0) {
    throw new RangeError('Withdrawal amount must be a finite number greater than zero');
  }

  return amount;
}

function monthBounds(month: string): { from: string; toExclusive: string; periodMonth: string } {
  const match = /^(\d{4})-(0[1-9]|1[0-2])$/.exec(month);

  if (!match) {
    throw new RangeError('Month must use YYYY-MM format');
  }

  const year = Number(match[1]);
  const monthNumber = Number(match[2]);
  const nextYear = monthNumber === 12 ? year + 1 : year;
  const nextMonth = monthNumber === 12 ? 1 : monthNumber + 1;
  const from = `${month}-01`;

  return {
    from,
    toExclusive: `${String(nextYear).padStart(4, '0')}-${String(nextMonth).padStart(2, '0')}-01`,
    periodMonth: from,
  };
}

function monthFromPeriodMonth(periodMonth: string): string {
  const match = /^(\d{4}-(?:0[1-9]|1[0-2]))-01$/.exec(periodMonth);

  if (!match) {
    throw new RangeError('Withdrawal period_month must be the first day of a calendar month');
  }

  return match[1];
}

function emptyResult(): AvailableMoneyResult {
  return {
    gameClub: { earned: 0, withdrawn: 0, available: 0, overdrawnBy: 0 },
    bar: { earned: 0, withdrawn: 0, available: 0, overdrawnBy: 0 },
    totalEarned: 0,
    totalWithdrawn: 0,
    totalAvailable: 0,
    hasOverWithdrawal: false,
    invalidWithdrawals: [],
  };
}

function isInRange(date: string, from: string, toExclusive: string): boolean {
  return date >= from && date < toExclusive;
}

function calculateMonthResult({
  cashRows,
  stockRows,
  purchaseRows,
  expenseRows,
  debtPaymentRows,
  withdrawalRows,
  periodMonth,
}: {
  cashRows: DailyCashRow[];
  stockRows: StockCountRow[];
  purchaseRows: StockPurchaseCostRow[];
  expenseRows: ExpenseRow[];
  debtPaymentRows: DebtPaymentValueRow[];
  withdrawalRows: AvailableMoneyWithdrawalRow[];
  periodMonth: string;
}): AvailableMoneyResult {
  withdrawalRows.forEach(withdrawalAmount);

  const gameClubCollections = cashRows.reduce(
    (sum, row) => sum
      + numericAmount(row.cash_income)
      + numericAmount(row.terminal_income)
      + numericAmount(row.card_income)
      + numericAmount(row.playstation_income ?? 0),
    0,
  );
  const debtCollections = debtPaymentRows.reduce(
    (sum, row) => sum + numericAmount(row.amount),
    0,
  );
  const barSales = stockRows.reduce(
    (sum, row) => sum + numericAmount(row.bar_income),
    0,
  );
  const qualifyingPurchases = purchaseRows.reduce(
    (sum, row) => row.date >= STOCK_PURCHASE_DEDUCTION_START_DATE
      ? sum + numericAmount(row.quantity) * numericAmount(row.cost_price)
      : sum,
    0,
  );
  const sourceExpenses = expenseRows.reduce<Record<OwnerWithdrawalSource, number>>(
    (totals, row) => {
      const source = row.payment_source === 'bar' ? 'bar' : 'game_club';
      totals[source] += numericAmount(row.amount);
      return totals;
    },
    { game_club: 0, bar: 0 },
  );
  const earnedBySource: Record<OwnerWithdrawalSource, number> = {
    game_club: gameClubCollections + debtCollections - sourceExpenses.game_club,
    bar: barSales - qualifyingPurchases - sourceExpenses.bar,
  };
  const withdrawalsBySource: Record<OwnerWithdrawalSource, number> = {
    game_club: 0,
    bar: 0,
  };
  const priorWithdrawals: Record<OwnerWithdrawalSource, number> = {
    game_club: 0,
    bar: 0,
  };
  const invalidWithdrawals: InvalidOwnerWithdrawal[] = [];
  const indexedWithdrawals = withdrawalRows
    .map((row, index) => ({ row, index }))
    .sort((a, b) =>
      (a.row.created_at ?? '').localeCompare(b.row.created_at ?? '')
      || (a.row.id ?? '').localeCompare(b.row.id ?? '')
      || a.index - b.index,
    );

  for (const { row } of indexedWithdrawals) {
    const amount = withdrawalAmount(row);
    const availableBefore = earnedBySource[row.source] - priorWithdrawals[row.source];
    const availableAfter = availableBefore - amount;

    if (availableAfter < 0) {
      invalidWithdrawals.push({
        id: row.id,
        period_month: periodMonth,
        source: row.source,
        amount,
        availableBefore,
        overdrawnBy: -availableAfter,
      });
    }

    priorWithdrawals[row.source] += amount;
    withdrawalsBySource[row.source] += amount;
  }

  const gameClubAvailable = earnedBySource.game_club - withdrawalsBySource.game_club;
  const barAvailable = earnedBySource.bar - withdrawalsBySource.bar;

  return {
    gameClub: {
      earned: earnedBySource.game_club,
      withdrawn: withdrawalsBySource.game_club,
      available: gameClubAvailable,
      overdrawnBy: Math.max(0, -gameClubAvailable),
    },
    bar: {
      earned: earnedBySource.bar,
      withdrawn: withdrawalsBySource.bar,
      available: barAvailable,
      overdrawnBy: Math.max(0, -barAvailable),
    },
    totalEarned: earnedBySource.game_club + earnedBySource.bar,
    totalWithdrawn: withdrawalsBySource.game_club + withdrawalsBySource.bar,
    totalAvailable: gameClubAvailable + barAvailable,
    hasOverWithdrawal: invalidWithdrawals.length > 0,
    invalidWithdrawals,
  };
}

/**
 * Computes the independent owner balances for one calendar month. Earnings or
 * withdrawals from any other month cannot cover this month's withdrawal.
 */
export function calculateAvailableMoneyForMonth({
  month,
  cashRows,
  stockRows,
  purchaseRows,
  expenseRows,
  debtPaymentRows = [],
  withdrawalRows = [],
}: CalculateAvailableMoneyForMonthInput): AvailableMoneyResult {
  const { from, toExclusive, periodMonth } = monthBounds(month);

  for (const row of withdrawalRows) monthFromPeriodMonth(row.period_month);

  return calculateMonthResult({
    cashRows: cashRows.filter((row) => isInRange(row.date, from, toExclusive)),
    stockRows: stockRows.filter((row) => isInRange(row.date, from, toExclusive)),
    purchaseRows: purchaseRows.filter((row) => isInRange(row.date, from, toExclusive)),
    expenseRows: expenseRows.filter((row) => isInRange(row.date, from, toExclusive)),
    debtPaymentRows: debtPaymentRows.filter((row) => isInRange(row.date, from, toExclusive)),
    withdrawalRows: withdrawalRows.filter((row) => row.period_month === periodMonth),
    periodMonth,
  });
}

/** Returns every populated month as an independently calculated bucket. */
export function calculateAvailableMoneyByMonth({
  cashRows,
  stockRows,
  purchaseRows,
  expenseRows,
  debtPaymentRows = [],
  withdrawalRows = [],
  throughDate,
}: CalculateAvailableMoneyInput): AvailableMoneyByMonth {
  const includedByDate = <T extends { date: string }>(rows: T[]): T[] =>
    throughDate === undefined ? rows : rows.filter((row) => row.date <= throughDate);
  const includedWithdrawalRows = withdrawalRows.filter((row) => {
    const month = monthFromPeriodMonth(row.period_month);
    return throughDate === undefined || month <= throughDate.slice(0, 7);
  });
  const includedCashRows = includedByDate(cashRows);
  const includedStockRows = includedByDate(stockRows);
  const includedPurchaseRows = includedByDate(purchaseRows);
  const includedExpenseRows = includedByDate(expenseRows);
  const includedDebtPaymentRows = includedByDate(debtPaymentRows);
  const months = new Set<string>();

  for (const row of includedCashRows) months.add(row.date.slice(0, 7));
  for (const row of includedStockRows) months.add(row.date.slice(0, 7));
  for (const row of includedPurchaseRows) months.add(row.date.slice(0, 7));
  for (const row of includedExpenseRows) months.add(row.date.slice(0, 7));
  for (const row of includedDebtPaymentRows) months.add(row.date.slice(0, 7));
  for (const row of includedWithdrawalRows) months.add(monthFromPeriodMonth(row.period_month));

  return Array.from(months).sort().reduce<AvailableMoneyByMonth>((results, month) => {
    results[month] = calculateAvailableMoneyForMonth({
      month,
      cashRows: includedCashRows,
      stockRows: includedStockRows,
      purchaseRows: includedPurchaseRows,
      expenseRows: includedExpenseRows,
      debtPaymentRows: includedDebtPaymentRows,
      withdrawalRows: includedWithdrawalRows,
    });
    return results;
  }, {});
}

/**
 * Sums the retained balances from independent month buckets. Unwithdrawn money
 * remains in the total, but a negative source/month bucket cannot reduce or be
 * covered by a positive bucket elsewhere. Aggregate `available` values are
 * therefore the sum of each bucket's positive withdrawable amount.
 */
export function sumAvailableMoneyResults(results: AvailableMoneyResult[]): AvailableMoneyResult {
  return results.reduce<AvailableMoneyResult>((total, result) => {
    total.gameClub.earned += result.gameClub.earned;
    total.gameClub.withdrawn += result.gameClub.withdrawn;
    total.gameClub.available += Math.max(0, result.gameClub.available);
    total.gameClub.overdrawnBy += result.gameClub.overdrawnBy;
    total.bar.earned += result.bar.earned;
    total.bar.withdrawn += result.bar.withdrawn;
    total.bar.available += Math.max(0, result.bar.available);
    total.bar.overdrawnBy += result.bar.overdrawnBy;
    total.totalEarned += result.totalEarned;
    total.totalWithdrawn += result.totalWithdrawn;
    total.totalAvailable = total.gameClub.available + total.bar.available;
    total.invalidWithdrawals.push(...result.invalidWithdrawals);
    total.hasOverWithdrawal = total.invalidWithdrawals.length > 0;
    return total;
  }, emptyResult());
}

/**
 * Computes totals across all supplied months while retaining month-level
 * isolation for overdraft validation.
 */
export function calculateAvailableMoney(input: CalculateAvailableMoneyInput): AvailableMoneyResult {
  return sumAvailableMoneyResults(Object.values(calculateAvailableMoneyByMonth(input)));
}
